january = [
    [
        "M 106",
        "Costellazione dei cani da caccia",
        "8,41",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Messier_106_by_Spitzer.jpg/560px-Messier_106_by_Spitzer.jpg",
    ],
    [
        "Ammasso lettera Y (NGC 1893)",
        "Costellazione dell'Auriga",
        "7,50",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/NGC_1893_Spitzer_View.jpg/440px-NGC_1893_Spitzer_View.jpg",
    ],
    [
        "IC 2169",
        "Costellazione dell'unicorno",
        "7,70",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/it/thumb/c/ca/IC_2169.jpg/560px-IC_2169.jpg",
    ],
    [
        "Nebulosa spirografo (IC 418)",
        "Costellazione della lepre",
        "9,44",
        "ASI ZWO 294MC PRO",
        "(1200+) mm",
        "https://upload.wikimedia.org/wikipedia/commons/6/6b/Spirograph_Nebula_-_Hubble_1999.jpg",
    ],
    [
        "NGC 2264",
        "Costellazione dell'unicorno",
        "3,9",
        "ASI ZWO 294MC PRO",
        "(420) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/NGC_2264_by_ESO.jpg/560px-NGC_2264_by_ESO.jpg",
    ],
    [
        "NGC 2282",
        "Costellazione dell'unicorno",
        "9,3",
        "ASI ZWO 294MC PRO",
        "(1200+) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/N2282s.jpg/600px-N2282s.jpg",
    ],
    [
        "NGC 2170",
        "Costellazione dell'unicorno",
        "9,50",
        "ASI ZWO 294MC PRO",
        "(420/800) mm",
        "https://upload.wikimedia.org/wikipedia/it/thumb/9/93/NGC_2170.jpg/560px-NGC_2170.jpg",
    ],
    [
        "IC 2177",
        "Costellazione dell'unicorno",
        "6,97",
        "ASI ZWO 294MC PRO",
        "(420) mm",
        "https://upload.wikimedia.org/wikipedia/it/thumb/5/5b/VdB_93.jpg/560px-VdB_93.jpg",
    ],
    [
        "Elmo di Thor (NGC 2359)",
        "Costellazione del cane maggiore",
        "11,45",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/NGC_2359.jpg/560px-NGC_2359.jpg",
    ],
    [
        "NGC 2440",
        "Costellazione della poppa",
        "9,40",
        "ASI ZWO 294MC PRO",
        "(1200+) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/NGC_2440_by_HST.jpg/560px-NGC_2440_by_HST.jpg",
    ],
]

february = [
    [
        "NGC 7662",
        "Costellazione di Andromeda",
        "8,30",
        "ASI ZWO 294MC PRO",
        "(1200+) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Ngc7662hst.jpg/530px-Ngc7662hst.jpg",
    ],
    [
        "Ammasso alveare (NGC 2632)",
        "Costellazione del Cancro",
        "3,10",
        "ASI ZWO 294MC PRO",
        "(420/800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/M44.jpg/560px-M44.jpg",
    ],
    [
        "M 48",
        "Costellazione dell'Idra",
        "5,80",
        "ASI ZWO 294MC PRO",
        "(420) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/M48a.jpg/560px-M48a.jpg",
    ],
    [
        "Nebulosa teschio (NGC 2467)",
        "Costellazione della Poppa",
        "7,10",
        "ASI ZWO 294MC PRO",
        "(420/800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/NGC_2467_and_Surroundings.jpg/560px-NGC_2467_and_Surroundings.jpg",
    ],
    [
        "M 47",
        "Costellazione della Poppa",
        "4,40",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Messier_047_2MASS.jpg/560px-Messier_047_2MASS.jpg",
    ],
    [
        "NGC 1514",
        "Costellazione del Toro",
        "10,19",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/4/4e/NGC1514.jpg",
    ],
    [
        "NGC 2392",
        "Costellazione dei Gemelli",
        "9,61",
        "ASI ZWO 294MC PRO",
        "(1200+) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Ngc2392.jpg/560px-Ngc2392.jpg",
    ],
    [
        "NGC 2506",
        "Costellazione dell'Unicorno",
        "7,60",
        "ASI ZWO 294MC PRO",
        "(420/800) mm",
        "https://upload.wikimedia.org/wikipedia/it/thumb/5/59/NGC_2506.png/560px-NGC_2506.png",
    ],
    [
        "IC 348",
        "Costellazione di Perseo",
        "7,30",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/it/thumb/9/9b/IC_348.jpg/560px-IC_348.jpg",
    ],
    [
        "NGC 1333",
        "Costellazione di Perseo",
        "9,50",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Ssc2005-24a.jpg/480px-Ssc2005-24a.jpg",
    ],
]

march = [
    [
        "M 49",
        "Costellazione della Vergine",
        "8,30",
        "ASI ZWO 294MC PRO",
        "(1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/a/a7/M49_3.6_5.8_8.0_microns_spitzer.png",
    ],
    [
        "M 61",
        "Costellazione della Vergine",
        "9,65",
        "ASI ZWO 294MC PRO",
        "(1200+) mm",
        "https://upload.wikimedia.org/wikipedia/commons/1/12/M61_3.6_5.8_8.0_microns_spitzer.png",
    ],
    [
        "NGC 4535",
        "Costellazione della Vergine",
        "9,73",
        "ASI ZWO 294MC PRO",
        "(1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/NGC_4535.jpg/440px-NGC_4535.jpg",
    ],
    [
        "M 90",
        "Costellazione della Vergine",
        "9,54",
        "ASI ZWO 294MC PRO",
        "(1200+) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Messier90_-_SDSS_DR14_%28panorama%29.jpg/560px-Messier90_-_SDSS_DR14_%28panorama%29.jpg",
    ],
    [
        "M 100",
        "Costellazione della Chioma di Berenice",
        "9,35",
        "ASI ZWO 294MC PRO",
        "(1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/5/5a/Spiral_Galaxy_M100.jpg",
    ],
    [
        "M 98",
        "Costellazione della Chioma di Berenice",
        "10,14",
        "ASI ZWO 294MC PRO",
        "(1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/M-98.jpg/560px-M-98.jpg",
    ],
    [
        "M 3",
        "Costellazione dei Cani da Caccia",
        "6,20",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/M3LRGB_891x674.jpg/560px-M3LRGB_891x674.jpg",
    ],
    [
        "M 53",
        "Costellazione della Chioma di Berenice",
        "7,70",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Messier_53_HST.jpg/560px-Messier_53_HST.jpg",
    ],
    [
        "M 87",
        "Costellazione della Vergine",
        "8,63",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/M87_jet.jpg/560px-M87_jet.jpg",
    ],
    [
        "NGC 4216",
        "Costellazione della Vergine",
        "10,01",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/N4216s.jpg/560px-N4216s.jpg",
    ],
]

april = [
    [
        "NGC 6210",
        "Costellazione di Ercole",
        "9.65",
        "ASI ZWO 294MC PRO",
        "(1200+) mm",
        "https://upload.wikimedia.org/wikipedia/commons/b/b3/Ngc6210a.jpg",
    ],
    [
        "M 92",
        "Costellazione di Ercole",
        "6.40",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Messier92_-_SDSS_DR14_%28panorama%29.jpg/560px-Messier92_-_SDSS_DR14_%28panorama%29.jpg",
    ],
    [
        "NGC 6229",
        "Costellazione di Ercole",
        "9.86",
        "ASI ZWO 294MC PRO",
        "(1200+) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/NGC_6229.jpg/560px-NGC_6229.jpg",
    ],
    [
        "NGC 6543",
        "Costellazione del Dragone",
        "8.10",
        "ASI ZWO 294MC PRO",
        "(1200+) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/NGC6543.jpg/560px-NGC6543.jpg",
    ],
    [
        "M 83",
        "Costellazione dell'Idra",
        "7.54",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/M83_-_Southern_Pinwheel.jpg/560px-M83_-_Southern_Pinwheel.jpg",
    ],
    [
        "NGC 5068",
        "Costellazione della Vergine",
        "9.90",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NGC_5068_HST_Wiki.jpg/507px-NGC_5068_HST_Wiki.jpg",
    ],
    [
        "M 68",
        "Costellazione dell'Idra",
        "7.30",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Messier_object_068.jpg/560px-Messier_object_068.jpg",
    ],
    [
        "NGC 4039",
        "Costellazione del Corvo",
        "11.08",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Antennae_galaxies_xl.jpg/560px-Antennae_galaxies_xl.jpg",
    ],
    [
        "NGC 3621",
        "Costellazione dell'Idra",
        "9.56",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/c/ce/NGC_3621SST.jpg",
    ],
    [
        "NGC 3242",
        "Costellazione dell'Idra",
        "8.60",
        "ASI ZWO 294MC PRO",
        "(1200+) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Ngc3242b.jpg/560px-Ngc3242b.jpg",
    ],
]

may = [
    [
        "M 84",
        "Costellazione della Vergine",
        "10.49",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/7/76/Messier84.jpg",
    ],
    [
        "M 65",
        "Costellazione del Leone",
        "10.25",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/4/47/M65.jpg",
    ],
    [
        "Galassia occhio di tigre (NGC 2841)",
        "Costellazione dell'Orsa Maggiore",
        "9.22",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/0/0c/NGC2841_3.6_5.8_8.0_microns_spitzer.png",
    ],
    [
        "Galassia girasole (M 63)",
        "Costellazione boreale dei Cani da Caccia",
        "8.59",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Messier_63.jpg/560px-Messier_63.jpg",
    ],
    [
        "Galassia vortice (M 51)",
        "Costellazione boreale dei Cani da Caccia",
        "8.10",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Messier51.jpg/560px-Messier51.jpg",
    ],
    [
        "Galassia sombrero (M 104)",
        "Costellazione della Vergine",
        "8",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/M104_ngc4594_sombrero_galaxy_hi-res.jpg/560px-M104_ngc4594_sombrero_galaxy_hi-res.jpg",
    ],
    [
        "Galassia girandola (M 101)",
        "Costellazione dell'Orsa Maggiore",
        "7.86",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/M101_hires_STScI-PRC2006-10a.jpg/560px-M101_hires_STScI-PRC2006-10a.jpg",
    ],
    [
        "Galassia di Bode (M 81)",
        "Costellazione dell'Orsa Maggiore",
        "6.94",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/M81_Galaxy_from_the_Mount_Lemmon_SkyCenter_Schulman_Telescope_courtesy_Adam_Block.jpg/560px-M81_Galaxy_from_the_Mount_Lemmon_SkyCenter_Schulman_Telescope_courtesy_Adam_Block.jpg",
    ],
    [
        "Ammasso di Ercole (M 13)",
        "Costellazione di Ercole",
        "5.80",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/M13LRGB_RC10.jpg/560px-M13LRGB_RC10.jpg",
    ],
    [
        "Luna 100% (target speciale)",
        "-",
        "-12.39",
        "I dati variano di molto in base al tipo di scatto",
        "I dati variano di molto in base al tipo di scatto",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/FullMoon2010.jpg/520px-FullMoon2010.jpg",
    ],
]

june = [
    [
        "NGC 7380",
        "Costellazione di Cefeo",
        "7.20",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/it/thumb/e/e6/Sh2-142.jpg/560px-Sh2-142.jpg",
    ],
    [
        "M 8",
        "Costellazione del Sagittario",
        "6.39",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Lagoon_Nebula_%28ESO%29.jpg/560px-Lagoon_Nebula_%28ESO%29.jpg",
    ],
    [
        "M 17",
        "Costellazione del Sagittario",
        "6.31",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Omega_Nebula.jpg/560px-Omega_Nebula.jpg",
    ],
    [
        "M 20",
        "Costellazione del Sagittario",
        "6.30",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Trifid.nebula.arp.750pix.jpg/560px-Trifid.nebula.arp.750pix.jpg",
    ],
    [
        "Nebulosa Aquila (M 16)",
        "Costellazione della Coda del Serpente",
        "6.29",
        "ASI ZWO 294MC PRO",
        "(420/800) mm",
        "https://upload.wikimedia.org/wikipedia/it/thumb/1/1d/Aquila-M16-NGC6611.jpg/446px-Aquila-M16-NGC6611.jpg",
    ],
    [
        "M 4",
        "Costellazione dello Scorpione",
        "5.90",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/5/5d/M4.jpg",
    ],
    [
        "M 22",
        "Costellazione del Sagittario",
        "5.10",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Messier22.jpg/480px-Messier22.jpg",
    ],
    [
        "IC 4592",
        "Costellazione dello Scorpione",
        "4",
        "ASI ZWO 294MC PRO",
        "(150/420) mm",
        "https://upload.wikimedia.org/wikipedia/it/thumb/c/c7/IC_4592.jpg/560px-IC_4592.jpg",
    ],
    [
        "IC 1396",
        "Costellazione di Cefeo",
        "3.5",
        "ASI ZWO 294MC PRO",
        "(200/800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/IC_1396_rev_20140921_s_%2818237481073%29.jpg/460px-IC_1396_rev_20140921_s_%2818237481073%29.jpg",
    ],
    [
        "Antares",
        "Costellazione dello Scorpione",
        "1.05",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/it/thumb/f/fc/Antares.jpg/520px-Antares.jpg",
    ],
]

july = [
    [
        "NGC 6946",
        "Costellazione del Cigno",
        "9.60",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Fireworks_Galaxis_Sig08-008.jpg/402px-Fireworks_Galaxis_Sig08-008.jpg",
    ],
    [
        "NGC 6822",
        "Costellazione del Sagittario",
        "8.10",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Barnard%27s_Galaxy.jpg/560px-Barnard%27s_Galaxy.jpg",
    ],
    [
        "M 27",
        "Costellazione della Volpe",
        "7.40",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Dumbbell_Nebula_M27_G%C3%B6ran_Nilsson_%26_The_Liverpool_Telescope.jpg/560px-Dumbbell_Nebula_M27_G%C3%B6ran_Nilsson_%26_The_Liverpool_Telescope.jpg",
    ],
    [
        "NGC 6823",
        "Costellazione della Volpe",
        "7.10",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Sh_2-86RGBHaRGBHunter.jpg/560px-Sh_2-86RGBHaRGBHunter.jpg",
    ],
    [
        "NGC 6992",
        "Costellazione del Cigno",
        "7",
        "ASI ZWO 294MC PRO",
        "(400) mm",
        "https://upload.wikimedia.org/wikipedia/it/thumb/5/53/Veilnebula.jpg/560px-Veilnebula.jpg",
    ],
    [
        "NGC 7023",
        "Costellazione di Cefeo",
        "6.80",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Iris1HunterWilson.jpg/560px-Iris1HunterWilson.jpg",
    ],
    [
        "M 6",
        "Costellazione dello Scorpione",
        "4.20",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/it/thumb/c/c6/Messier6.jpg/560px-Messier6.jpg",
    ],
    [
        "NGC 7000",
        "Costellazione del Cigno",
        "4",
        "ASI ZWO 294MC PRO",
        "(90) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/North-America-nebula.jpeg/406px-North-America-nebula.jpeg",
    ],
    [
        "Saturno",
        "-",
        "0.37 (indicativa)",
        "ASI ZWO 224MC",
        "(4000) mm - In base alla mia attrezzatura",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Saturn_%28planet%29_large.jpg/387px-Saturn_%28planet%29_large.jpg",
    ],
    [
        "Giove",
        "-",
        "-2.65 (indicativa)",
        "ASI ZWO 224MC",
        "(4000) mm - In base alla mia attrezzatura",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Jupiter_and_its_shrunken_Great_Red_Spot.jpg/520px-Jupiter_and_its_shrunken_Great_Red_Spot.jpg",
    ],
]

august = [
    [
        "IC 63",
        "Costellazione di Cassiopea",
        "13.33",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/it/thumb/6/6e/Sh-2_185.jpg/560px-Sh-2_185.jpg",
    ],
    [
        "NGC 7635",
        "Costellazione di Cassiopea",
        "10",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/The_Bubble_Nebula_-_NGC_7635_-_Heic1608a.tif/lossy-page1-560px-The_Bubble_Nebula_-_NGC_7635_-_Heic1608a.tif.jpg",
    ],
    [
        "IC 10",
        "Costellazione di Cassiopea",
        "9.50",
        "ASI ZWO 294MC PRO",
        "(1200+) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/IC10_BVHa.jpg/560px-IC10_BVHa.jpg",
    ],
    [
        "IC 342",
        "Costellazione della Giraffa",
        "9.10",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/IC342_RGB2.jpg/560px-IC342_RGB2.jpg",
    ],
    [
        "IC 5146",
        "Costellazione del Cigno",
        "7.20",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/IC5146_The_Cocoon_Nebula.jpg/560px-IC5146_The_Cocoon_Nebula.jpg",
    ],
    [
        "IC 1805",
        "Costellazione di Cassiopea",
        "6.50",
        "ASI ZWO 294MC PRO",
        "(400) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Heart_Nebula_IC_1805_NGC_896.jpg/560px-Heart_Nebula_IC_1805_NGC_896.jpg",
    ],
    [
        "IC 1848",
        "Costellazione di Cassiopea",
        "6.50",
        "ASI ZWO 294MC PRO",
        "(350) mm",
        "https://upload.wikimedia.org/wikipedia/it/thumb/a/a8/Ic1848_01.jpg/560px-Ic1848_01.jpg",
    ],
    [
        "M 15",
        "Costellazione di Pegaso",
        "6.30",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Messier_15_HST.jpg/560px-Messier_15_HST.jpg",
    ],
    [
        "Galassia del Triangolo (M 33)",
        "Costellazione del Triangolo",
        "5.72",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/M33.jpg/560px-M33.jpg",
    ],
    [
        "Galassia di Andromeda (M 31)",
        "Costellazione di Andromeda",
        "3.44",
        "ASI ZWO 294MC PRO",
        "(250) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Andromeda_Galaxy_%28with_h-alpha%29.jpg/560px-Andromeda_Galaxy_%28with_h-alpha%29.jpg",
    ],
]

semptember = [
    [
        "NGC 1055",
        "Costellazione della Balena",
        "10.59",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/NGC_1055_-_Eso1707a.tiff/lossy-page1-440px-NGC_1055_-_Eso1707a.tiff.jpg",
    ],
    [
        "NGC 1333",
        "Costellazione di Perseo",
        "9.50",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Ssc2005-24a.jpg/480px-Ssc2005-24a.jpg",
    ],
    [
        "NGC 7793",
        "Costellazione dello Scultore",
        "9.11",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/NGC_7793SpitzerFull.jpg/560px-NGC_7793SpitzerFull.jpg",
    ],
    [
        "NGC 247",
        "Costellazione della Balena",
        "9.11",
        "ASI ZWO 294MC PRO",
        "(>800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Wide_Field_Imager_view_of_the_spiral_galaxy_NGC_247.jpg/560px-Wide_Field_Imager_view_of_the_spiral_galaxy_NGC_247.jpg",
    ],
    [
        "NGC 1579",
        "Costellazione di Perseo",
        "8.50",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/NGC_1579_The_Trifid_of_the_North.jpg/440px-NGC_1579_The_Trifid_of_the_North.jpg",
    ],
    [
        "NGC 253",
        "Costellazione dello Scultore",
        "8.48",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Sculptor_Galaxy_by_VISTA.jpg/560px-Sculptor_Galaxy_by_VISTA.jpg",
    ],
    [
        "NGC 288",
        "Costellazione dello Scultore",
        "8.13",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/NGC_288_Hubble_WikiSky.jpg/560px-NGC_288_Hubble_WikiSky.jpg",
    ],
    [
        "NGC 7293",
        "Costellazione dell'Aquario",
        "7.60",
        "ASI ZWO 294MC PRO",
        "(420/800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/NGC7293_%282004%29.jpg/557px-NGC7293_%282004%29.jpg",
    ],
    [
        "NGC 1499",
        "Costellazione di Perseo",
        "6",
        "ASI ZWO 294MC PRO",
        "(150) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/California-nebula.jpeg/560px-California-nebula.jpeg",
    ],
    [
        "Pleiadi (M 45)",
        "Costellazione del Toro",
        "1.20",
        "ASI ZWO 294MC PRO",
        "(420) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Pleiades_large.jpg/560px-Pleiades_large.jpg",
    ],
]

october = [
    [
        "NGC 488",
        "Costellazione dei Pesci",
        "10.96",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/N488s.jpg/560px-N488s.jpg",
    ],
    [
        "NGC 936",
        "Costellazione della Balena",
        "10.81",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Potw1009a.jpg/560px-Potw1009a.jpg",
    ],
    [
        "NGC 134",
        "Costellazione dello Scultore",
        "10.12",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Phot-49-07.jpg/560px-Phot-49-07.jpg",
    ],
    [
        "NGC 2403",
        "Costellazione della Giraffa",
        "8.90",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/NGC_2403HST.jpg/560px-NGC_2403HST.jpg",
    ],
    [
        "M 77",
        "Costellazione della Balena",
        "8.87",
        "ASI ZWO 294MC PRO",
        "(1200+) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Messier_77_spiral_galaxy_by_HST.jpg/560px-Messier_77_spiral_galaxy_by_HST.jpg",
    ],
    [
        "M 1",
        "Costellazione del Toro",
        "8.40",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Crab_Nebula.jpg/560px-Crab_Nebula.jpg",
    ],
    [
        "M 83",
        "Costellazione dell'Idra",
        "8.13",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/M83_-_Southern_Pinwheel.jpg/560px-M83_-_Southern_Pinwheel.jpg",
    ],
    [
        "NGC 55",
        "Costellazione dello Scultore",
        "7.87",
        "ASI ZWO 294MC PRO",
        "(420/800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/ESO_NGC_55_3point6-m_copy.jpg/560px-ESO_NGC_55_3point6-m_copy.jpg",
    ],
    [
        "NGC 1555",
        "Costellazione del Toro",
        "6.50",
        "ASI ZWO 294MC PRO",
        "(1200+) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/N1555s.jpg/560px-N1555s.jpg",
    ],
    [
        "IC 405",
        "Costellazione dell'Auriga",
        "6",
        "ASI ZWO 294MC PRO",
        "(420/800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/FlamingStarHunterWilson.jpg/560px-FlamingStarHunterWilson.jpg",
    ],
]

november = [
    [
        "IC 443",
        "Costellazione dei Gemelli",
        "12",
        "ASI ZWO 294MC PRO",
        "(420/800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/IC443.jpeg/560px-IC443.jpeg",
    ],
    [
        "NGC 4236",
        "Costellazione del Dragone",
        "10.55",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/7/77/NGC_4236_I_FUV_g2006.jpg",
    ],
    [
        "NGC 3077",
        "Costellazione dell'Orsa Maggiore",
        "10.14",
        "ASI ZWO 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/NGC_3077_Hubble.jpg/500px-NGC_3077_Hubble.jpg",
    ],
    [
        "NGC 1788",
        "Costellazione di Orione",
        "10.11",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/ESO-NGC1788.jpg/560px-ESO-NGC1788.jpg",
    ],
    [
        "NGC 1931",
        "Costellazione dell'Auriga",
        "10.1",
        "ASI ZWO 294MC PRO",
        "(1200+) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/NGC1931HunterWilson.jpg/560px-NGC1931HunterWilson.jpg",
    ],
    [
        "IC 410",
        "Costellazione dell'Auriga",
        "10",
        "ASI ZWO 294MC PRO",
        "(420) mm",
        "https://upload.wikimedia.org/wikipedia/it/thumb/d/d2/IC_410.jpg/560px-IC_410.jpg",
    ],
    [
        "NGC 6914",
        "Costellazione del Cigno",
        "9.84",
        "ASI ZWO 294MC PRO",
        "(150/420) mm",
        "https://upload.wikimedia.org/wikipedia/it/thumb/e/e2/NGC_6914.jpg/560px-NGC_6914.jpg",
    ],
    [
        "NGC 2158",
        "Costellazione dei Gemelli",
        "8.6",
        "ASI ZWO 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/NGC2158_-_SDSS_DR14_%28panorama%29.jpg/560px-NGC2158_-_SDSS_DR14_%28panorama%29.jpg",
    ],
    [
        "Nebulosa Testa di Strega (NGC 1909)",
        "Costellazione di Eridano",
        "8",
        "ASI ZWO 294MC PRO",
        "(150) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Reflection.nebula.arp.750pix.jpg/456px-Reflection.nebula.arp.750pix.jpg",
    ],
    [
        "NGC 6960",
        "Costellazione del Cigno",
        "7",
        "ASI ZWO 294MC PRO",
        "(420) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Veil_Nebula_-_NGC6960.jpg/700px-Veil_Nebula_-_NGC6960.jpg",
    ],
]


december = [
    [
        "Nebulosa Pipistrello Cosmico (NGC 1788)",
        "Costellazione di Orione",
        "10,11",
        "ASI 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/ESO-NGC1788.jpg/560px-ESO-NGC1788.jpg",
    ],
    [
        "Nebulosa 13ma Perla (NGC 1999)",
        "Costellazione di Orione",
        "9,83",
        "ASI 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/7/7f/Ngc1999.jpg",
    ],
    [
        "Nebulosa occhio di Cleopatra (NGC 1535)",
        "Costellazione di Eridano",
        "9,60",
        "ASI 294MC PRO",
        "(1200+) mm",
        "https://upload.wikimedia.org/wikipedia/commons/7/70/NGC1535-hst-R814GB555.jpg",
    ],
    [
        "Nebulosa Rosetta (NGC 2238)",
        "Costellazione dell’unicorno",
        "9,00",
        "ASI 294MC PRO",
        "(420) mm",
        "https://upload.wikimedia.org/wikipedia/commons/8/8f/Rosette_Nebula_NGC_2237_-_C49.png",
    ],
    [
        "Nebulosa del Granchio (M 1)",
        "Costellazione del Toro",
        "8,40",
        "ASI 294MC PRO",
        "(800/1200) mm",
        "https://upload.wikimedia.org/wikipedia/commons/0/00/Crab_Nebula.jpg",
    ],
    [
        "Nebulosa Casper (M 78)",
        "Costellazione di Orione",
        "8,30",
        "ASI 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/a/ac/M78a.jpg",
    ],
    [
        "Nebulosa Testa di Scimmia (NGC 2174)",
        "Costellazione di Orione",
        "7",
        "ASI 294MC PRO",
        "(800) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/NGC-2174.tif/lossy-page1-2880px-NGC-2174.tif.jpg",
    ],
    [
        "Nebulosa Testa Di Cavallo (Barnard 33)",
        "Costellazione di Orione",
        "6,8",
        "ASI 294MC PRO",
        "(420) mm",
        "https://upload.wikimedia.org/wikipedia/commons/6/68/Barnard_33.jpg",
    ],
    [
        "Nebulosa Di Orione (M 42)",
        "Costellazione di Orione",
        "4",
        "ASI 294MC PRO",
        "(300/420) mm",
        "https://www.universoastronomia.com/wp-content/uploads/2019/11/M42Detailed_DrudisGoldman_960.jpg",
    ],
    [
        "Nebulosa Fiamma (NGC 2024)",
        "Costellazione di Orione",
        "2",
        "ASI 294MC PRO",
        "(420) mm",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/The_hidden_fires_of_the_Flame_Nebula.jpg/493px-The_hidden_fires_of_the_Flame_Nebula.jpg",
    ],
]

targets_month = {
    "january": january,
    "february": february,
    "march": march,
    "april": april,
    "may": may,
    "june": june,
    "july": july,
    "august": august,
    "september": semptember,
    "october": october,
    "november": november,
    "december": december,
}

italian_months = {
    "january": "Gennaio",
    "february": "Febbraio",
    "march": "Marzo",
    "april": "Aprile",
    "may": "Maggio",
    "june": "Giugno",
    "july": "Luglio",
    "august": "Agosto",
    "september": "Settembre",
    "october": "Ottobre",
    "november": "Novembre",
    "december": "Dicembre",
}

